# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: JanFiala.PSPad.507.32b
PackageVersion: 5.0.7.775
InstallerType: inno
Installers:
- InstallerUrl: https://pspad.poradna.net/release/pspad507_setup.exe
  Architecture: x86
  InstallerSha256: C9A743C79B3FC79B39CFC96441501ABC119D724BB1DC7DE76D4C97643D0974E2
ManifestType: installer
ManifestVersion: 1.6.0
